title: Maak een hoogste score
hero_image: images/banner.png
description: Leer hoe je een hoogste score kunt bijhouden voor je Scratch-spel
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Stap een
