---
title: Создать высокий балл
hero_image: Изображения / banner.png
description: Узнайте, как создать высокий балл для вашей игры Scratch
theme: красный
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: создатель, дизайн-0, программирование-0, физика-комп-0, производство-0, сообщество-0
interests: "игры"
technologies: "царапина"
site_areas:
steps:
  - 
    title: Первый шаг
