---
title: Lag en høy poengsum
hero_image: images / banner.png
description: Lær hvordan du lager en høy poengsum for ditt Scratch-spill
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaperen, design-0, programmering-0, phys-comp-0, produksjon-0, fellesskap-0
interests: "spill"
technologies: "ripe"
site_areas:
steps:
  - 
    title: Steg en
