---
title: Tạo điểm số cao
hero_image: images / banner.png
description: Tìm hiểu cách tạo điểm số cao cho trò chơi Scratch của bạn
theme: đỏ
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tác giả, thiết kế-0, lập trình-0, phys-comp-0, sản xuất-0, cộng đồng-0
interests: "Trò chơi"
technologies: "vết trầy"
site_areas:
steps:
  - 
    title: Bước một
