---
title: Lav en høj score
hero_image: images / banner.png
description: Lær, hvordan du laver en høj score for dit Scratch-spil
theme: rød
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skaber, design-0, programmering-0, phys-comp-0, fremstilling-0, community-0
interests: "spil"
technologies: "kradse"
site_areas:
steps:
  - 
    title: Trin et
