---
title: Criar um registo de melhor pontuação
hero_image: images/banner.png
description: Aprende a criar um registo de melhor pontuação para o teu jogo Scratch
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - 
    title: Primeiro passo
