---
title: Cria um registo de melhor pontuação
hero_image: images/banner.png
description: Aprende a criar o registo de melhor pontuação para o teu jogo Scratch
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, design-0, programação-0, phys-comp-0, manufacture-0, community-0
interests: "jogos"
technologies: "scratch"
site_areas:
steps:
  - 
    title: Primeiro passo
