---
title: 创建高分
hero_image: images/banner.png
description: 学习如何为你的 Scratch 游戏创建高分
theme: 红色
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: 创建者, 设计-0, 编程-0, 物理组装-0, 制造-0, 社区-0
interests: "游戏"
technologies: "scratch"
site_areas:
steps:
  - 
    title: 第一步
