title: Spremi najbolji rezultat
hero_image: images/banner.png
description: Saznaj kako spremiti najbolji rezultat u Scratch igri
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Prvi korak
