---
title: Luo korkea pisteet
hero_image: Kuvien / banner.png
description: Opi luomaan korkea pistemäärä Scratch-pelille
theme: punainen
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: luoja, design-0, ohjelmointi-0, phys-comp-0, valmistus-0, yhteisö-0
interests: "pelit"
technologies: "naarmu"
site_areas: ""
steps:
  - 
    title: Ensimmäinen askel
