---
title: Crea una puntuaci칩n m치xima
hero_image: images / banner.png
description: Aprende a crear una puntuaci칩n m치xima para tu juego en Scratch
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - 
    title: Paso uno
