---
title: Crea un puntaje alto
hero_image: images / banner.png
description: Aprende a crear un puntaje alto para tu juego Scratch
theme: rojo
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creador, dise침o-0, programaci칩n-0, phys-comp-0, fabricaci칩n-0, comunidad-0
interests: "juegos"
technologies: "rasgu침o"
site_areas: ""
steps:
  - 
    title: Paso uno
