---
title: Creu sgôr uchel
hero_image: delweddau / banner.png
description: Dysgwch sut i greu sgôr uchel ar gyfer eich gêm Scratch
theme: Coch
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: crewr, dylunio-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "gemau"
technologies: "crafu"
site_areas:
steps:
  - 
    title: Cam un
