---
title: Creu sgôr uchel
hero_image: images/banner.png
description: Dysgwch sut i greu sgôr uchel ar gyfer eich gêm Scratch
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "gemau"
technologies: "scratch"
site_areas:
steps:
  - 
    title: Cam un
