---
title: Erstelle einen höchsten Punktstand
hero_image: images/banner.png
description: So erstellst du einen höchsten Punkstand für dein Scratch-Spiel
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Schritt eins
