---
title: Erstellen Sie eine hohe Punktzahl
hero_image: Bilder / Banner.png
description: Erfahren Sie, wie Sie eine hohe Punktzahl für Ihr Scratch-Spiel erstellen
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: Schöpfer, Design-0, Programmierung-0, Phys-Comp-0, Herstellung-0, Community-0
interests: "Spiele"
technologies: "kratzen"
site_areas: ""
steps:
  - 
    title: Schritt eins
