---
title: Erstellen Sie eine hohe Punktzahl
hero_image: images/banner.png
description: Erfahren Sie, wie Sie eine hohe Punktzahl für Ihr Scratch-Spiel erstellen
theme: rot
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "kratzen"
site_areas:
steps:
  - 
    title: Schritt eins
