---
title: Creați un clasament
hero_image: images / banner.png
description: Învățați cum să creați un clasament pentru jocul Scratch
theme: roșu
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programare-0, fiz-comp-0, fabricare-0, comunitate-0
interests: "jocuri"
technologies: "zgârietură"
site_areas: ""
steps:
  - 
    title: Pasul unu
