---
title: Crie uma pontuação elevada
hero_image: images / banner.png
description: Saiba como criar uma pontuação elevada para o seu jogo Scratch
theme: vermelho
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: criador, design-0, programação-0, phys-comp-0, manufacture-0, community-0
interests: "jogos"
technologies: "coçar, arranhão"
site_areas: ""
steps:
  - 
    title: Passo um
