---
title: Crie uma pontuação máxima
hero_image: images/banner.png
description: Aprenda a criar o registo de pontuação máxima para o seu jogo no Scratch
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Primeiro passo
