---
title: Ustvarite visok rezultat
hero_image: images / banner.png
description: Naučite se, kako ustvariti visok rezultat za svojo igro Scratch
theme: rdeča
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: ustvarjalec, design-0, programiranje-0, fiz-comp-0, izdelava-0, skupnost-0
interests: "igre"
technologies: "praska"
site_areas: ""
steps:
  - 
    title: Prvi korak
