---
title: Hozz létre rekord pontszámot
hero_image: images/banner.png
description: Tanuld meg, hogyan lehet rekord pontszámot létrehozni a Scratch játékodhoz
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "games"
technologies: "scratch"
site_areas:
steps:
  - title: Első lépés
