---
title: Hozzon létre magas pontszámot
hero_image: images / banner.png
description: Ismerje meg, hogyan lehet magas pontszámot létrehozni a Scratch játékhoz
theme: piros
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: alkotó, design-0, programozás-0, fiz-comp-0, gyártás-0, community-0
interests: "játékok"
technologies: "karcolás"
site_areas:
steps:
  - 
    title: Első lépés
