---
title: 創造一個高分
hero_image: 圖片/ banner.png
description: 了解如何為您的Scratch遊戲創造高分
theme: 紅
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: 創作者，設計-0，編程-0，物理comp-0，製造-0，社區-0
interests: "遊戲"
technologies: "刮"
site_areas:
steps:
  - 
    title: 步驟1
