---
title: Utwórz wysoki wynik
hero_image: images / banner.png
description: Dowiedz się, jak stworzyć najlepszy wynik w grze Scratch
theme: czerwony
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: twórca, design-0, programowanie-0, phys-comp-0, production-0, community-0
interests: "Gry"
technologies: "zadraśnięcie"
site_areas:
steps:
  - 
    title: Krok pierwszy
