---
title: Vytvorte vysoké skóre
hero_image: images / banner.png
description: Zistite, ako vytvoriť vysoké skóre pre hru Scratch
theme: červená
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: tvorca, dizajn-0, programovanie-0, phys-comp-0, výroba-0, komunita-0
interests: "hry"
technologies: "škrabanec"
site_areas: ""
steps:
  - 
    title: Krok jedna
