---
title: Skapa ett högt betyg
hero_image: images / banner.png
description: Lär dig hur du skapar ett högt poäng för ditt Scratch-spel
theme: röd
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: skapare, design-0, programmering-0, phys-comp-0, tillverkning-0, community-0
interests: "spel"
technologies: "repa"
site_areas:
steps:
  - 
    title: Steg ett
