---
title: Buat skor tinggi
hero_image: imej / banner.png
description: Ketahui cara membuat skor tinggi untuk permainan Scratch anda
theme: merah
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: pencipta, reka bentuk-0, pengaturcaraan-0, phys-comp-0, pembuatan-0, komuniti-0
interests: "permainan"
technologies: "awal"
site_areas:
steps:
  - 
    title: Langkah satu
