---
title: Δημιούργησε ένα υψηλό σκορ
hero_image: images/banner.png
description: Μάθε πώς μπορείς να δημιουργήσεις ένα υψηλό σκορ για το παιχνίδι Scratch
theme: κόκκινο
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: δημιουργός, σχεδιασμός-0, προγραμματισμός-0, phys-comp-0, κατασκευή-0, κοινότητα-0
interests: "Παιχνίδια"
technologies: "scratch"
site_areas: ""
steps:
  - 
    title: Βήμα πρώτο
