---
title: Créer un score élevé
hero_image: images / banner.png
description: Apprenez comment créer un score élevé pour votre jeu Scratch
theme: rouge
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: créateur, design-0, programmation-0, phys-comp-0, fabrication-0, communauté-0
interests: "jeux"
technologies: "scratch"
site_areas:
steps:
  - 
    title: La première étape
