---
title: Yüksek puan oluştur
hero_image: images / banner.png
description: Scratch oyununuz için yüksek skoru nasıl oluşturacağınızı öğrenin
theme: kırmızı
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programlama-0, fiz-comp-0, production-0, topluluk-0
interests: "oyunlar"
technologies: "çizik"
site_areas: ""
steps:
  - 
    title: Adım bir
