---
title: Yüksek puan oluşturun
hero_image: images/banner.png
description: Scratch oyununuz için yüksek puanın nasıl oluşturulacağını öğrenin
theme: red
duration: 1
listed: false
ingredient: true
copyedit: true
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
interests: "oyunlar"
technologies: "scratch"
site_areas:
steps:
  - 
    title: Birinci adım
